language: c
os: linux
dist: bionic
arch: amd64
jobs:
  include:
  - name: PostgreSQL 14
    compiler: gcc
    addons:
      apt:
        packages:
        - postgresql-14
        - postgresql-server-dev-14
    script:
    - sudo make install -j$(nproc)
    - make installcheck
    after_failure: cat regress/regression.diffs
