name: Build / Regression

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest commit id of PostgreSQL 18
        run: |
          echo "PG_COMMIT_HASH=$(git ls-remote https://git.postgresql.org/git/postgresql.git refs/heads/REL_18_STABLE | awk '{print $1}')" >> $GITHUB_ENV

      - name: Cache PostgreSQL 18
        uses: actions/cache@v3
        id: pg18cache
        with:
          path: ~/pg18
          key: ${{ runner.os }}-v1-pg18-${{ env.PG_COMMIT_HASH }}

      - name: Install necessary dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libreadline-dev zlib1g-dev flex bison

      - name: Install PostgreSQL 18 and some extensions
        if: steps.pg18cache.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 --branch REL_18_STABLE https://git.postgresql.org/git/postgresql.git ~/pg18source
          cd ~/pg18source
          ./configure --prefix=$HOME/pg18 CFLAGS="-std=gnu99 -ggdb -O0" --enable-cassert
          make install -j$(nproc) > /dev/null
          cd contrib
          cd fuzzystrmatch
          make PG_CONFIG=$HOME/pg18/bin/pg_config install -j$(nproc) > /dev/null
          cd ../pg_trgm
          make PG_CONFIG=$HOME/pg18/bin/pg_config install -j$(nproc) > /dev/null

      - uses: actions/checkout@v3

      - name: Build AGE
        id: build
        run: |
          make PG_CONFIG=$HOME/pg18/bin/pg_config install -j$(nproc)

      - name: Pull and build pgvector
        id: pgvector
        run: |
          git clone https://github.com/pgvector/pgvector.git
          cd pgvector
          make PG_CONFIG=$HOME/pg18/bin/pg_config install -j$(nproc) > /dev/null

      - name: Regression tests
        id: regression_tests
        run: |
          make PG_CONFIG=$HOME/pg18/bin/pg_config installcheck EXTRA_TESTS="pgvector fuzzystrmatch pg_trgm"
        continue-on-error: true

      - name: Dump regression test errors
        if: steps.regression_tests.outcome != 'success'
        run: |
          echo "Dump section begin."
          cat $HOME/work/age/age/regress/regression.diffs
          echo "Dump section end."
          exit 1
