name: JDBC Driver Tests

on:
  push:
    branches: [ "Dev_Multiple_Labels" ]

  pull_request:
    branches: [ "Dev_Multiple_Labels" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: drivers/jdbc

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Build and Test
      run: gradle build
